### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by TuriGuilano** [NathanNeelis/meesterproef-2021#10]
Hi - 
Please write an extensive flow of the project in your readme and provide comments in each file. Especially for code reviews - otherwise there is no in depth code review - which is a pity

**Comment by NathanNeelis** [comment]
Hi,
Solved in the readme. 
You can read all about the code structure [here](https://github.com/NathanNeelis/meesterproef-2021#code-structure).
A bit late for the code reviews, but then again, I am not able to do magic like Harry Potter 🧙  and had to make priorities.
