### ISSUE TITLE
Vars at the top!

### ISSUE THREAD

**Issue by ju5tu5** [NathanNeelis/meesterproef-2021#2]
Het is netjes je variabelen (en constanten) bovenin je bestand te declareren, je kunt eventueel in secties opdelen door een witregel te gebruiken. Het codebestand leest nu warrig omdat ik geen overzicht heb van het geheel... (ik moet zeg maar 2x variabelen in memory laden ;) )

https://github.com/NathanNeelis/meesterproef-2021/blob/2075893aa068d9b6e1f6a924a600f8858f60f923/server.js#L32

**Comment by NathanNeelis** [comment]
Fixed :tada: 
Helemaal gelijk, het was een beetje rommelig.
Nog wat extra comments toegevoegd en alles geordend.  
Bedankt voor de feedback.
