### ISSUE TITLE
Semantiek

### ISSUE THREAD

**Issue by ju5tu5** [NathanNeelis/meesterproef-2021#3]
Zijn &lt;div&gt; en &lt;span&gt; semantisch gezien de beste keuzes voor een overzicht? Het lijkt op tabulaire informatie, ik denk dan meestal aan een &lt;table&gt; ;)

https://github.com/NathanNeelis/meesterproef-2021/blob/2075893aa068d9b6e1f6a924a600f8858f60f923/views/includes/daily_overview.ejs#L8

**Comment by NathanNeelis** [comment]
Je hebt helemaal gelijk, ik heb nog even goed naar de semantiek gekeken en hier en daar wat updates gemaakt.
Bedankt voor de feedback.
