### ISSUE TITLE
Semantiek

### ISSUE THREAD

**Issue by ju5tu5** [NathanNeelis/meesterproef-2021#4]
Dit punt geld algemener ook. Check de semantiek van je HTML..

Hier is bijvoorbeeld een lijst met links: https://github.com/NathanNeelis/meesterproef-2021/blob/2075893aa068d9b6e1f6a924a600f8858f60f923/views/includes/heavy_activities.ejs#L1

**Comment by NathanNeelis** [comment]
Je hebt helemaal gelijk, ik heb nog even goed naar de semantiek gekeken en hier en daar wat updates gemaakt.
Bedankt voor de feedback.
